# Stuff in here is to tell verilator to include
# Autogenerated on Thu Oct 23 03:25:13 PM CDT 2025 from /home/jonathan/SPEX-128/src by generate_filelist.sh
# WARNING: You might need to manually change the order of the files. Order is 
#          heuristic (packages first). If build fails due to type/interface order,
#          manually reorder this file so defining units appear before users.
/home/jonathan/SPEX-128/src/packages/float_flag_pkg.sv
/home/jonathan/SPEX-128/src/packages/sp_mode_pkg.sv
/home/jonathan/SPEX-128/src/packages/float_metadata_pkg.sv
/home/jonathan/SPEX-128/src/float_to_fixed.sv
