# Stuff in here is to tell verilator to include
# Autogenerated on Wed Oct 22 10:52:15 PM CDT 2025 from /home/jonathan/SPEX-128/src by generate_filelist.sh
/home/jonathan/SPEX-128/src/float_flag_pkg.sv
/home/jonathan/SPEX-128/src/float_to_fixed.sv
