#!/usr/bin/env bash
# Generate a per-test filelist.f under the *current* directory (module test dir).
# Defaults:
#   - Include ALL packages under src/packages (.sv and .svh)
#   - Include ONLY <module>.sv, where <module> = basename of $PWD
# Options:
#   --module NAME            Override module name (without .sv)
#   --all                    Include all non-package *.sv under src
#   --also NAME_OR_PATH      Additionally include another module file (repeatable)
#   --out FILE               Output path (default: $PWD/filelist.f)
#   --src DIR                Override src dir (default: <repo_root>/src)
#   --verbose                Print decisions
#   -h|--help

set -euo pipefail

usage() {
  cat <<EOF
Usage: $(basename "$0") [--module NAME] [--all] [--also NAME_OR_PATH ...] [--out FILE] [--src DIR] [--verbose]
Generates a filelist.f for the current test folder (defaults to \$PWD/filelist.f).
By default, includes all packages and only <module>.sv (module = basename of \$PWD).
EOF
}

# --- repo layout discovery (location-independent) ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"           # .../tests/svunit
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd -P)"                              # repo root
SRC="${ROOT}/src"
PKG_DIR="${SRC}/packages"

# --- defaults ---
MODULE="$(basename "$PWD")"
OUTFILE="${PWD%/}/filelist.f"
INCLUDE_ALL=0
VERBOSE=0
declare -a ALSOS=()

# --- args ---
while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) usage; exit 0 ;;
    --module) MODULE="${2:-}"; shift 2 ;;
    --all) INCLUDE_ALL=1; shift ;;
    --also) ALSOS+=("${2:-}"); shift 2 ;;
    --out) OUTFILE="${2:-}"; shift 2 ;;
    --src) SRC="${2:-}"; PKG_DIR="${SRC}/packages"; shift 2 ;;
    --verbose) VERBOSE=1; shift ;;
    *) echo "Unknown arg: $1" >&2; usage; exit 2 ;;
  esac
done

# --- sanity ---
[[ -d "$SRC" ]] || { echo "src not found: $SRC" >&2; exit 1; }
[[ -d "$PKG_DIR" ]] || { echo "packages dir not found: $PKG_DIR" >&2; exit 1; }
mkdir -p "$(dirname "$OUTFILE")"

# --- helpers ---
abspath() {
  if command -v realpath >/dev/null 2>&1; then realpath "$1"
  elif command -v readlink >/dev/null 2>&1; then readlink -f "$1" 2>/dev/null || python3 - "$1" <<'PY'
import os, sys; print(os.path.realpath(sys.argv[1]))
PY
  else
    python3 - "$1" <<'PY'
import os, sys; print(os.path.realpath(sys.argv[1]))
PY
  fi
}

resolve_mod_or_path() {
  local arg="$1"
  local cand=""
  if [[ "$arg" = /* ]]; then
    cand="$arg"
  elif [[ "$arg" == *".sv" || "$arg" == *"/"* ]]; then
    # relative file/path -> resolve relative to SRC if not absolute
    if [[ -f "$arg" ]]; then
      cand="$arg"
    elif [[ -f "$SRC/$arg" ]]; then
      cand="$SRC/$arg"
    else
      cand="$arg"  # will fail later with a nice error
    fi
  else
    cand="$SRC/$arg.sv"
  fi
  [[ -f "$cand" ]] || { echo "Not found: $cand (from '$arg')" >&2; exit 2; }
  abspath "$cand"
}

# --- collect list ---
declare -a PKG_FILES=()
declare -a MOD_FILES=()

# packages (.sv and .svh), sorted
while IFS= read -r -d '' f; do PKG_FILES+=("$(abspath "$f")"); done < <(
  find "$PKG_DIR" -maxdepth 1 -type f \( -name '*.sv' -o -name '*.svh' \) -print0 | LC_ALL=C sort -z
)

# modules / non-packages
if [[ $INCLUDE_ALL -eq 1 ]]; then
  while IFS= read -r -d '' f; do MOD_FILES+=("$(abspath "$f")"); done < <(
    find "$SRC" -type f -name '*.sv' ! -path "$PKG_DIR/*" -print0 | LC_ALL=C sort -z
  )
else
  # only <module>.sv (+ any --also ...)
  MAIN="$(resolve_mod_or_path "$MODULE")"
  MOD_FILES+=("$MAIN")
  for a in "${ALSOS[@]}"; do
    MOD_FILES+=("$(resolve_mod_or_path "$a")")
  done
  # de-duplicate while preserving order
  declare -A seen=()
  declare -a uniq=()
  for x in "${MOD_FILES[@]}"; do
    [[ -n "${seen["$x"]+y}" ]] && continue
    seen["$x"]=1; uniq+=("$x")
  done
  MOD_FILES=("${uniq[@]}")
fi

# --- write header ---
{
  echo "# Filelist for simulator include"
  echo "# Autogenerated on $(date) from $SRC by gen_filelist.sh"
  echo "# Policy: packages first; then modules; final ordering refined by reorder_filelist.sh"
} > "$OUTFILE"

# --- write packages ---
for p in "${PKG_FILES[@]}"; do echo "$p"; done >> "$OUTFILE"

# --- write modules (non-packages) ---
for m in "${MOD_FILES[@]}"; do echo "$m"; done >> "$OUTFILE"

[[ $VERBOSE -eq 1 ]] && {
  echo "Wrote $(wc -l < "$OUTFILE") lines to $OUTFILE"
  echo "Module: $MODULE"
  echo "All non-packages: $INCLUDE_ALL"
  printf 'Also: %s\n' "${ALSOS[*]:-<none>}"
}
