#!/usr/bin/env bash
# Generate a Verilator filelist with absolute paths for all SystemVerilog files in ./src
# Order: files under src/packages first, then everything else
# Output: ./tests/svunit/filelist.f

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd -P)"
SRC="$ROOT/src"
PKG_DIR="$SRC/packages"
OUTDIR="$ROOT/tests/svunit"
OUTFILE="$OUTDIR/filelist.f"

abspath() {
  if command -v realpath >/dev/null 2>&1; then realpath "$1"
  elif command -v readlink >/dev/null 2>&1; then readlink -f "$1" 2>/dev/null || python3 - "$1" <<'PY'
import os, sys; print(os.path.realpath(sys.argv[1]))
PY
  else
    python3 - "$1" <<'PY'
import os, sys; print(os.path.realpath(sys.argv[1]))
PY
  fi
}

[[ -d "$SRC" ]] || { echo "src folder not found at: $SRC" >&2; exit 1; }
mkdir -p "$OUTDIR"

# Warning (stderr, so CI logs show it)
echo "WARNING: You might need to manually change the order of the files." >&2

# Header with warning (in-file comment)
{
  echo "# Stuff in here is to tell simulator what to include"
  echo "# Autogenerated on $(date) from $SRC by generate_filelist.sh"
  echo "# WARNING: You might need to manually change the order of the files. Order is "
  echo "#          heuristic (packages first). If build fails due to type/interface order,"
  echo "#          manually reorder this file so defining units appear before users."
} > "$OUTFILE"

# 1) Files inside src/packages (if present)
if [[ -d "$PKG_DIR" ]]; then
  find "$PKG_DIR" -type f \( -name '*.sv' -o -name '*.svh' \) -print0 \
    | LC_ALL=C sort -z \
    | while IFS= read -r -d '' f; do
        echo "$(abspath "$f")" >> "$OUTFILE"
      done
fi

# 2) Files NOT inside src/packages
find "$SRC" -type f \( -name '*.sv' -o -name '*.svh' \) ! -path "$PKG_DIR/*" -print0 \
  | LC_ALL=C sort -z \
  | while IFS= read -r -d '' f; do
      echo "$(abspath "$f")" >> "$OUTFILE"
    done

echo "Wrote $(wc -l < "$OUTFILE") lines to $OUTFILE"
