#!/usr/bin/env python3
"""
This script is generated by ChatGPT to convert .hex RAM initialization files to
.data (binary) files for $readmemb.
"""

import argparse
from pathlib import Path
import sys
from typing import List


def iter_data_lines(path: Path) -> List[str]:
    lines: List[str] = []
    with path.open() as handle:
        for raw in handle:
            line = raw.split("//", 1)[0].split("#", 1)[0].strip()
            if not line:
                continue
            if line.startswith("@"):
                raise ValueError(f"{path}: address directives not supported: {line}")
            lines.append(line)
    return lines


def nibble_to_bits(ch: str) -> str:
    if ch.isdigit() or ("a" <= ch.lower() <= "f"):
        return format(int(ch, 16), "04b")
    if ch in "xX":
        return "xxxx"
    if ch in "zZ":
        return "zzzz"
    if ch == "?":
        return "????"
    raise ValueError(f"Unsupported hex character '{ch}'")


def hex_line_to_bits(line: str) -> str:
    return "".join(nibble_to_bits(ch) for ch in line)


def convert_file(src: Path, dst: Path) -> None:
    lines = iter_data_lines(src)
    if not lines:
        return
    width = len(lines[0]) * 4
    for line in lines:
        if len(line) * 4 != width:
            raise ValueError(f"{src}: inconsistent line width (expected {width} bits)")
    dst.parent.mkdir(parents=True, exist_ok=True)
    with dst.open("w") as handle:
        for line in lines:
            handle.write(hex_line_to_bits(line))
            handle.write("\n")


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(
        description="Convert .hex RAM init files to .data (binary) files."
    )
    parser.add_argument(
        "--src",
        type=Path,
        default=root / "tests/svunit/SPEX128_top",
        help="Directory containing .hex files.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=root / "ram_init_data",
        help="Output directory for .data files.",
    )
    parser.add_argument(
        "--pattern",
        default="fixed*partition.hex",
        help="Glob pattern of files to convert.",
    )
    args = parser.parse_args()

    if not args.src.is_dir():
        print(f"Source directory not found: {args.src}", file=sys.stderr)
        return 1

    files = sorted(args.src.glob(args.pattern))
    if not files:
        print(f"No files matched {args.pattern} in {args.src}", file=sys.stderr)
        return 1

    args.out.mkdir(parents=True, exist_ok=True)
    for path in files:
        out_path = args.out / f"{path.stem}.data"
        convert_file(path, out_path)

    print(f"Converted {len(files)} file(s) to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
