/********************************************************************
 *
 * Originator   : Jonathan Tan feat. ChatGPT 5.2 Codex
 * Date         : 1/12/2026
 *
 ********************************************************************
 *
 * Description:
 * Parameterized LUT module for partitions across SINGLE/TWO/FOUR
 * sp_modes. Supports optional sign-bit handling for partition A and
 * optional 128->64/32 conversion when desired.
 * 
 * AI Use: This module is entirely written by ChatGPT with little
 *         modification by myself, however, the code is generated by
 *         based on all my previous work (hence the coding style is
 *         quite similar to my own).
 * 
 ********************************************************************
 * 
 * Modification history:
 *       Ver   |  Who       |  Date	       |  Changes
 *     ------- + ---------- + ------------ + -----------------------
 *       1.00  |  Jonathan  |  1/8/2026    |  Birth of this file
 * 
 *******************************************************************/

import float_flag_pkg::*;
import sp_mode_pkg::*;
import float_metadata_pkg::*;
import binary128_pkg::*;
import binary64_pkg::*;
import binary32_pkg::*;
import binary128_convert_pkg::*;
import fixed128_pkg::*;
import fixed64_pkg::*;
import fixed32_pkg::*;

/**
 * Some parts of this module is written in a way that make this module highly reusable
 * whether you want to use 128 reusable LUT or not, and those parts are gated by parameters
 * which the synthesizer should be smart enough to exclude when compiling, as long as you
 * set the correct parameter flags. But to be safe this macro gates the compilation of those
 * parts if needed.
 * 
 * When this macro is set, those lines of code will be excluded by the compilation like a c
 * macro and will not be included in the synthesized hardware, hence "hardware" "blockout".
 */
// `define HARDWARE_BLOCKOUT

module fixed_partition_sp #(
  // Behavior controls
  parameter bit HAS_SIGN          = 1'b0, // MSB is sign bit when set
  parameter bit USE_128_FOR_64    = 1'b0, // derive 64 outputs from 128 LUT
  parameter bit USE_128_FOR_32    = 1'b0, // derive 32 outputs from 128 LUT
  parameter bit ENABLE_64         = 1'b1,
  parameter bit ENABLE_32         = 1'b1,

  // Address widths (excluding sign bit)
  parameter int ADDR_BITS_128     = 13,
  parameter int ADDR_BITS_64      = 13,
  parameter int ADDR_BITS_32      = 10,
  parameter int LANE_BITS_128     = ADDR_BITS_128 + (HAS_SIGN ? 1 : 0),
  parameter int LANE_BITS_64      = ADDR_BITS_64  + (HAS_SIGN ? 1 : 0),
  parameter int LANE_BITS_32      = ADDR_BITS_32  + (HAS_SIGN ? 1 : 0),

  // LUT files (use *_POS/_NEG when HAS_SIGN=1, otherwise *_FILE)
  parameter string INIT_128_POS_FILE = "",
  parameter string INIT_128_NEG_FILE = "",
  parameter string INIT_128_FILE     = "",
  parameter string INIT_64_POS_FILE  = "",
  parameter string INIT_64_NEG_FILE  = "",
  parameter string INIT_64_FILE      = "",
  parameter string INIT_32_POS_FILE  = "",
  parameter string INIT_32_NEG_FILE  = "",
  parameter string INIT_32_FILE      = "",

  // Error and debug parameters
  parameter int ERROR_SIGNAL_NUM_BITS = 32,
  parameter int DEBUG_SIGNAL_NUM_BITS = 32,

  // Identifier const
  parameter logic [3:0] MODULE_IDENTIFIER = 4'b0000
) (
  input   logic                                   i_clk,
  input   logic                                   i_rst_n, // Synchronous

  // Metadata stuff
  input   var float_metadata_t                    i_metadata,
  output  var float_metadata_t                    o_metadata,

  // Data inputs by mode
  input   logic [LANE_BITS_128-1:0]               i_lane_128,
  input   logic [LANE_BITS_64-1:0]                i_lane_64a,
  input   logic [LANE_BITS_64-1:0]                i_lane_64b,
  input   logic [LANE_BITS_32-1:0]                i_lane_32a,
  input   logic [LANE_BITS_32-1:0]                i_lane_32b,
  input   logic [LANE_BITS_32-1:0]                i_lane_32c,
  input   logic [LANE_BITS_32-1:0]                i_lane_32d,

  // Data outputs
  output  binary128_t                             o_exp_a128,
  output  binary64_t                              o_exp_a64a,
  output  binary64_t                              o_exp_a64b,
  output  binary32_t                              o_exp_a32a,
  output  binary32_t                              o_exp_a32b,
  output  binary32_t                              o_exp_a32c,
  output  binary32_t                              o_exp_a32d,

  // Upstream Handshake
  input   logic                                   i_valid128,
  input   logic                                   i_valid64a,
  input   logic                                   i_valid64b,
  input   logic                                   i_valid32a,
  input   logic                                   i_valid32b,
  input   logic                                   i_valid32c,
  input   logic                                   i_valid32d,

  // Downstream Handshake
  output  logic                                   o_valid128,
  output  logic                                   o_valid64a,
  output  logic                                   o_valid64b,
  output  logic                                   o_valid32a,
  output  logic                                   o_valid32b,
  output  logic                                   o_valid32c,
  output  logic                                   o_valid32d,

  // Module identifier
  output  logic [3:0]                             o_sanity_identifier,

  // Error and debug signals
  output  logic [ERROR_SIGNAL_NUM_BITS-1:0]       o_error,
  output  logic [DEBUG_SIGNAL_NUM_BITS-1:0]       o_debug
);

localparam int DEPTH_128 = (ADDR_BITS_128 > 0) ? (1 << ADDR_BITS_128) : 1;
localparam int DEPTH_64  = (ADDR_BITS_64  > 0) ? (1 << ADDR_BITS_64)  : 1;
localparam int DEPTH_32  = (ADDR_BITS_32  > 0) ? (1 << ADDR_BITS_32)  : 1;

//=====================================================================================
// Module body
//=====================================================================================

// Default stuff out
logic [DEBUG_SIGNAL_NUM_BITS-1:0]   s_o_debug;
logic [ERROR_SIGNAL_NUM_BITS-1:0]   s_o_error;
always_ff @( posedge i_clk ) begin : defaulter
  if (!i_rst_n) begin
    s_o_error <= '0;
    s_o_debug <= '0;
  end
end

/**
 * FSM
 */
typedef enum logic [1:0] {
  S0_IDLE     = 2'b00,
  S1          = 2'b01,
  S2          = 2'b10,
  S3          = 2'b11
} state_t;
state_t s_curr_state, s_next_state;
always_ff @( posedge i_clk ) begin : fixed_partition_FSM
  if (!i_rst_n) begin
    s_curr_state <= S0_IDLE;
  end
  else begin
    s_curr_state <= s_next_state;
  end
end

/**
 *
 * State transition control
 *
 */
logic s_S0_en, s_S1_en, s_S2_en, s_S3_en;
always_comb begin : stage_en_control
  // Defaults
  s_next_state = s_curr_state;
  s_S0_en = '0;
  s_S1_en = '0;
  s_S2_en = '0;
  s_S3_en = '0;

  unique case (s_curr_state)
    S0_IDLE: begin
      if ( i_valid128 |
          (i_valid64a & i_valid64b) |                           // "all-or-nothing" rule
          (i_valid32a & i_valid32b & i_valid32c & i_valid32d)   // "all-or-nothing" rule
         ) begin
        s_next_state = S1;
      end
    end
    S1: begin
      s_S1_en = 1'b1;
      s_next_state = S2;
    end
    S2: begin
      s_S2_en = 1'b1;
      s_next_state = S0_IDLE;
    end
    default: begin
      s_next_state = S0_IDLE;
    end
  endcase
end

//=====================================================================================
// LUTs
//=====================================================================================
(* rom_style = "block" *) binary128_t mem128_pos  [0:DEPTH_128-1];
(* rom_style = "block" *) binary128_t mem128_neg  [0:DEPTH_128-1];
`ifndef HARDWARE_BLOCKOUT
(* rom_style = "block" *) binary64_t  mem64_pos   [0:DEPTH_64-1];
(* rom_style = "block" *) binary64_t  mem64_neg   [0:DEPTH_64-1];
(* rom_style = "block" *) binary32_t  mem32_pos   [0:DEPTH_32-1];
(* rom_style = "block" *) binary32_t  mem32_neg   [0:DEPTH_32-1];
`endif

initial begin
  if (HAS_SIGN) begin
    if (INIT_128_POS_FILE != "") $readmemh(INIT_128_POS_FILE, mem128_pos);
    if (INIT_128_NEG_FILE != "") $readmemh(INIT_128_NEG_FILE, mem128_neg);
  end
  else begin
    if (INIT_128_FILE != "") $readmemh(INIT_128_FILE, mem128_pos);
  end
end

`ifndef HARDWARE_BLOCKOUT
generate
  if (ENABLE_64) begin : init64
    initial begin
      if (HAS_SIGN) begin
        if (INIT_64_POS_FILE != "") $readmemh(INIT_64_POS_FILE, mem64_pos);
        if (INIT_64_NEG_FILE != "") $readmemh(INIT_64_NEG_FILE, mem64_neg);
      end
      else begin
        if (INIT_64_FILE != "") $readmemh(INIT_64_FILE, mem64_pos);
      end
    end
  end
endgenerate

generate
  if (ENABLE_32) begin : init32
    initial begin
      if (HAS_SIGN) begin
        if (INIT_32_POS_FILE != "") $readmemh(INIT_32_POS_FILE, mem32_pos);
        if (INIT_32_NEG_FILE != "") $readmemh(INIT_32_NEG_FILE, mem32_neg);
      end
      else begin
        if (INIT_32_FILE != "") $readmemh(INIT_32_FILE, mem32_pos);
      end
    end
  end
endgenerate
`endif

//=====================================================================================
// Stage 1: Read LUTs
//=====================================================================================
binary128_t s_stage1a_exp_a128;
binary128_t s_stage1a_exp_a64a_128;
binary128_t s_stage1a_exp_a64b_128;
binary64_t  s_stage1a_exp_a64a_64;
binary64_t  s_stage1a_exp_a64b_64;
binary128_t s_stage1a_exp_a32a_128;
binary128_t s_stage1a_exp_a32b_128;
binary32_t  s_stage1a_exp_a32a_32;
binary32_t  s_stage1a_exp_a32b_32;

always_ff @( posedge i_clk ) begin : stage1a
  if (!i_rst_n) begin
    s_stage1a_exp_a128   <= '0;
    s_stage1a_exp_a64a_128 <= '0;
    s_stage1a_exp_a64b_128 <= '0;
    s_stage1a_exp_a64a_64  <= '0;
    s_stage1a_exp_a64b_64  <= '0;
    s_stage1a_exp_a32a_128 <= '0;
    s_stage1a_exp_a32b_128 <= '0;
    s_stage1a_exp_a32a_32  <= '0;
    s_stage1a_exp_a32b_32  <= '0;
  end
  else begin
    if (s_S1_en) begin
      case (i_metadata.sp_mode)
        SINGLE_MODE: begin
          if (i_valid128 === 1'b1) begin
            if (HAS_SIGN) begin
              if (i_lane_128[LANE_BITS_128-1] === 1'b0) begin
                s_stage1a_exp_a128 <= mem128_pos[i_lane_128[ADDR_BITS_128-1:0]];
              end
              else begin
                s_stage1a_exp_a128 <= mem128_neg[i_lane_128[ADDR_BITS_128-1:0]];
              end
            end
            else begin
              s_stage1a_exp_a128 <= mem128_pos[i_lane_128[ADDR_BITS_128-1:0]];
            end
          end
        end // SINGLE_MODE

        TWO_SP_MODE: begin
          if (ENABLE_64 && i_valid64a === 1'b1 && i_valid64b === 1'b1) begin
            if (USE_128_FOR_64) begin
              if (HAS_SIGN) begin
                if (i_lane_64a[LANE_BITS_64-1] === 1'b0) begin
                  s_stage1a_exp_a64a_128 <= mem128_pos[i_lane_64a[ADDR_BITS_128-1:0]];
                end
                else begin
                  s_stage1a_exp_a64a_128 <= mem128_neg[i_lane_64a[ADDR_BITS_128-1:0]];
                end

                if (i_lane_64b[LANE_BITS_64-1] === 1'b0) begin
                  s_stage1a_exp_a64b_128 <= mem128_pos[i_lane_64b[ADDR_BITS_128-1:0]];
                end
                else begin
                  s_stage1a_exp_a64b_128 <= mem128_neg[i_lane_64b[ADDR_BITS_128-1:0]];
                end
              end
              else begin
                s_stage1a_exp_a64a_128 <= mem128_pos[i_lane_64a[ADDR_BITS_128-1:0]];
                s_stage1a_exp_a64b_128 <= mem128_pos[i_lane_64b[ADDR_BITS_128-1:0]];
              end
            end
            else begin
`ifndef HARDWARE_BLOCKOUT
              if (HAS_SIGN) begin
                if (i_lane_64a[LANE_BITS_64-1] === 1'b0) begin
                  s_stage1a_exp_a64a_64 <= mem64_pos[i_lane_64a[ADDR_BITS_64-1:0]];
                end
                else begin
                  s_stage1a_exp_a64a_64 <= mem64_neg[i_lane_64a[ADDR_BITS_64-1:0]];
                end

                if (i_lane_64b[LANE_BITS_64-1] === 1'b0) begin
                  s_stage1a_exp_a64b_64 <= mem64_pos[i_lane_64b[ADDR_BITS_64-1:0]];
                end
                else begin
                  s_stage1a_exp_a64b_64 <= mem64_neg[i_lane_64b[ADDR_BITS_64-1:0]];
                end
              end
              else begin
                s_stage1a_exp_a64a_64 <= mem64_pos[i_lane_64a[ADDR_BITS_64-1:0]];
                s_stage1a_exp_a64b_64 <= mem64_pos[i_lane_64b[ADDR_BITS_64-1:0]];
              end
`endif
            end
          end
        end // TWO_SP_MODE

        FOUR_SP_MODE: begin
          if (ENABLE_32 &&
              i_valid32a === 1'b1 && i_valid32b === 1'b1 &&
              i_valid32c === 1'b1 && i_valid32d === 1'b1) begin
            if (USE_128_FOR_32) begin
              if (HAS_SIGN) begin
                if (i_lane_32a[LANE_BITS_32-1] === 1'b0) begin
                  s_stage1a_exp_a32a_128 <= mem128_pos[i_lane_32a[ADDR_BITS_128-1:0]];
                end
                else begin
                  s_stage1a_exp_a32a_128 <= mem128_neg[i_lane_32a[ADDR_BITS_128-1:0]];
                end

                if (i_lane_32b[LANE_BITS_32-1] === 1'b0) begin
                  s_stage1a_exp_a32b_128 <= mem128_pos[i_lane_32b[ADDR_BITS_128-1:0]];
                end
                else begin
                  s_stage1a_exp_a32b_128 <= mem128_neg[i_lane_32b[ADDR_BITS_128-1:0]];
                end
              end
              else begin
                s_stage1a_exp_a32a_128 <= mem128_pos[i_lane_32a[ADDR_BITS_128-1:0]];
                s_stage1a_exp_a32b_128 <= mem128_pos[i_lane_32b[ADDR_BITS_128-1:0]];
              end
            end
            else begin
`ifndef HARDWARE_BLOCKOUT
              if (HAS_SIGN) begin
                if (i_lane_32a[LANE_BITS_32-1] === 1'b0) begin
                  s_stage1a_exp_a32a_32 <= mem32_pos[i_lane_32a[ADDR_BITS_32-1:0]];
                end
                else begin
                  s_stage1a_exp_a32a_32 <= mem32_neg[i_lane_32a[ADDR_BITS_32-1:0]];
                end

                if (i_lane_32b[LANE_BITS_32-1] === 1'b0) begin
                  s_stage1a_exp_a32b_32 <= mem32_pos[i_lane_32b[ADDR_BITS_32-1:0]];
                end
                else begin
                  s_stage1a_exp_a32b_32 <= mem32_neg[i_lane_32b[ADDR_BITS_32-1:0]];
                end
              end
              else begin
                s_stage1a_exp_a32a_32 <= mem32_pos[i_lane_32a[ADDR_BITS_32-1:0]];
                s_stage1a_exp_a32b_32 <= mem32_pos[i_lane_32b[ADDR_BITS_32-1:0]];
              end
`endif
            end
          end
        end // FOUR_SP_MODE

        default: begin
          assert (0) else begin
            s_o_error[0] <= 1'b1;
          end
        end
      endcase
    end
  end
end

/**
 * Stage 1b block: Propogate valid bit and metadata bits
 */
logic             s_stage1b_valid128;
logic             s_stage1b_valid64a;
logic             s_stage1b_valid64b;
logic             s_stage1b_valid32a;
logic             s_stage1b_valid32b;
logic             s_stage1b_valid32c;
logic             s_stage1b_valid32d;
float_metadata_t  s_stage1b_metadata;
always_ff @( posedge i_clk ) begin : stage1b
  if (!i_rst_n) begin
    s_stage1b_valid128 <= '0;
    s_stage1b_valid64a <= '0;
    s_stage1b_valid64b <= '0;
    s_stage1b_valid32a <= '0;
    s_stage1b_valid32b <= '0;
    s_stage1b_valid32c <= '0;
    s_stage1b_valid32d <= '0;
    s_stage1b_metadata <= '0;
  end
  else begin
    s_stage1b_valid128 <= s_S1_en & i_valid128;
    s_stage1b_valid64a <= s_S1_en & i_valid64a;
    s_stage1b_valid64b <= s_S1_en & i_valid64b;
    s_stage1b_valid32a <= s_S1_en & i_valid32a;
    s_stage1b_valid32b <= s_S1_en & i_valid32b;
    s_stage1b_valid32c <= s_S1_en & i_valid32c;
    s_stage1b_valid32d <= s_S1_en & i_valid32d;
    s_stage1b_metadata <= i_metadata;
  end
end

//=====================================================================================
// Stage 2
//=====================================================================================
binary128_t  s_stage2a_exp_a128;
binary64_t   s_stage2a_exp_a64a;
binary64_t   s_stage2a_exp_a64b;
binary32_t   s_stage2a_exp_a32a;
binary32_t   s_stage2a_exp_a32b;
binary128_t  s_stage2a_exp_a32c_128;
binary128_t  s_stage2a_exp_a32d_128;
binary32_t   s_stage2a_exp_a32c_32;
binary32_t   s_stage2a_exp_a32d_32;

always_ff @( posedge i_clk ) begin : stage2a
  if (!i_rst_n) begin
    s_stage2a_exp_a128   <= '0;
    s_stage2a_exp_a64a   <= '0;
    s_stage2a_exp_a64b   <= '0;
    s_stage2a_exp_a32a   <= '0;
    s_stage2a_exp_a32b   <= '0;
    s_stage2a_exp_a32c_128 <= '0;
    s_stage2a_exp_a32d_128 <= '0;
    s_stage2a_exp_a32c_32  <= '0;
    s_stage2a_exp_a32d_32  <= '0;
  end
  else begin
    if (s_S2_en) begin
      case (s_stage1b_metadata.sp_mode)
        SINGLE_MODE: begin
          s_stage2a_exp_a128 <= s_stage1a_exp_a128;
        end

        TWO_SP_MODE: begin
          if (ENABLE_64) begin
            if (USE_128_FOR_64) begin
              s_stage2a_exp_a64a <= binary128_to_binary64_rne(s_stage1a_exp_a64a_128);
              s_stage2a_exp_a64b <= binary128_to_binary64_rne(s_stage1a_exp_a64b_128);
            end
            else begin
              s_stage2a_exp_a64a <= s_stage1a_exp_a64a_64;
              s_stage2a_exp_a64b <= s_stage1a_exp_a64b_64;
            end
          end
        end

        FOUR_SP_MODE: begin
          if (ENABLE_32 &&
              i_valid32a === 1'b1 && i_valid32b === 1'b1 &&
              i_valid32c === 1'b1 && i_valid32d === 1'b1) begin
            if (USE_128_FOR_32) begin
              if (HAS_SIGN) begin
                if (i_lane_32c[LANE_BITS_32-1] === 1'b0) begin
                  s_stage2a_exp_a32c_128 <= mem128_pos[i_lane_32c[ADDR_BITS_128-1:0]];
                end
                else begin
                  s_stage2a_exp_a32c_128 <= mem128_neg[i_lane_32c[ADDR_BITS_128-1:0]];
                end

                if (i_lane_32d[LANE_BITS_32-1] === 1'b0) begin
                  s_stage2a_exp_a32d_128 <= mem128_pos[i_lane_32d[ADDR_BITS_128-1:0]];
                end
                else begin
                  s_stage2a_exp_a32d_128 <= mem128_neg[i_lane_32d[ADDR_BITS_128-1:0]];
                end
              end
              else begin
                s_stage2a_exp_a32c_128 <= mem128_pos[i_lane_32c[ADDR_BITS_128-1:0]];
                s_stage2a_exp_a32d_128 <= mem128_pos[i_lane_32d[ADDR_BITS_128-1:0]];
              end
            end
            else begin
`ifndef HARDWARE_BLOCKOUT
              if (HAS_SIGN) begin
                if (i_lane_32c[LANE_BITS_32-1] === 1'b0) begin
                  s_stage2a_exp_a32c_32 <= mem32_pos[i_lane_32c[ADDR_BITS_32-1:0]];
                end
                else begin
                  s_stage2a_exp_a32c_32 <= mem32_neg[i_lane_32c[ADDR_BITS_32-1:0]];
                end

                if (i_lane_32d[LANE_BITS_32-1] === 1'b0) begin
                  s_stage2a_exp_a32d_32 <= mem32_pos[i_lane_32d[ADDR_BITS_32-1:0]];
                end
                else begin
                  s_stage2a_exp_a32d_32 <= mem32_neg[i_lane_32d[ADDR_BITS_32-1:0]];
                end
              end
              else begin
                s_stage2a_exp_a32c_32 <= mem32_pos[i_lane_32c[ADDR_BITS_32-1:0]];
                s_stage2a_exp_a32d_32 <= mem32_pos[i_lane_32d[ADDR_BITS_32-1:0]];
              end
`endif
            end
          end

          if (ENABLE_32) begin
            if (USE_128_FOR_32) begin
              s_stage2a_exp_a32a <= binary128_to_binary32_rne(s_stage1a_exp_a32a_128);
              s_stage2a_exp_a32b <= binary128_to_binary32_rne(s_stage1a_exp_a32b_128);
            end
            else begin
              s_stage2a_exp_a32a <= s_stage1a_exp_a32a_32;
              s_stage2a_exp_a32b <= s_stage1a_exp_a32b_32;
            end
          end
        end

        default: begin
          assert (0) else begin
            s_o_error[1] <= 1'b1;
          end
        end
      endcase
    end
  end
end

/**
 * Stage 2b block: Propogate valid bit and metadata bits
 */
logic             s_stage2b_valid128;
logic             s_stage2b_valid64a;
logic             s_stage2b_valid64b;
logic             s_stage2b_valid32a;
logic             s_stage2b_valid32b;
logic             s_stage2b_valid32c;
logic             s_stage2b_valid32d;
float_metadata_t  s_stage2b_metadata;
always_ff @( posedge i_clk ) begin : stage2b
  if (!i_rst_n) begin
    s_stage2b_valid128 <= '0;
    s_stage2b_valid64a <= '0;
    s_stage2b_valid64b <= '0;
    s_stage2b_valid32a <= '0;
    s_stage2b_valid32b <= '0;
    s_stage2b_valid32c <= '0;
    s_stage2b_valid32d <= '0;
    s_stage2b_metadata <= '0;
  end
  else begin
    s_stage2b_valid128 <= s_stage1b_valid128;
    s_stage2b_valid64a <= s_stage1b_valid64a;
    s_stage2b_valid64b <= s_stage1b_valid64b;
    s_stage2b_valid32a <= s_stage1b_valid32a;
    s_stage2b_valid32b <= s_stage1b_valid32b;
    s_stage2b_valid32c <= s_stage1b_valid32c;
    s_stage2b_valid32d <= s_stage1b_valid32d;
    s_stage2b_metadata <= s_stage1b_metadata;
  end
end

//=====================================================================================
// Final assignment
//=====================================================================================
assign o_metadata = s_stage2b_metadata;
assign o_exp_a128 = s_stage2a_exp_a128;
assign o_exp_a64a = ENABLE_64 ? s_stage2a_exp_a64a : '0;
assign o_exp_a64b = ENABLE_64 ? s_stage2a_exp_a64b : '0;
assign o_exp_a32a = ENABLE_32 ? s_stage2a_exp_a32a : '0;
assign o_exp_a32b = ENABLE_32 ? s_stage2a_exp_a32b : '0;

generate
  if (ENABLE_32 && USE_128_FOR_32) begin : gen_out32_from128
    assign o_exp_a32c = binary128_to_binary32_rne(s_stage2a_exp_a32c_128);
    assign o_exp_a32d = binary128_to_binary32_rne(s_stage2a_exp_a32d_128);
  end
  else if (ENABLE_32) begin : gen_out32_from32
    assign o_exp_a32c = s_stage2a_exp_a32c_32;
    assign o_exp_a32d = s_stage2a_exp_a32d_32;
  end
  else begin : gen_out32_zero
    assign o_exp_a32c = '0;
    assign o_exp_a32d = '0;
  end
endgenerate

assign o_valid128 = s_stage2b_valid128;
assign o_valid64a = ENABLE_64 ? s_stage2b_valid64a : 1'b0;
assign o_valid64b = ENABLE_64 ? s_stage2b_valid64b : 1'b0;
assign o_valid32a = ENABLE_32 ? s_stage2b_valid32a : 1'b0;
assign o_valid32b = ENABLE_32 ? s_stage2b_valid32b : 1'b0;
assign o_valid32c = ENABLE_32 ? s_stage2b_valid32c : 1'b0;
assign o_valid32d = ENABLE_32 ? s_stage2b_valid32d : 1'b0;
assign o_sanity_identifier = MODULE_IDENTIFIER;
assign o_error = s_o_error;
assign o_debug = s_o_debug;

endmodule
